services:
  db:
    hostname: db
    image: postgres:alpine
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=coaxis_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
