defmodule Coaxis.Repo.Migrations.AddImpactThesisResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:impact_theses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :problem_addressed, :text
      add :proposed_solution, :text
      add :target_beneficiaries, :text
      add :project_novelty, :text
      add :negative_impacts, :text
      add :early_successes, :text
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    drop table(:impact_theses)
  end
end