defmodule Coaxis.Repo.Migrations.AddIntentTypeToProject do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :intent_tupe, :text, default: "venture"
    end
  end

  def down do
    alter table(:projects) do
      remove :intent_tupe
    end
  end
end
