defmodule Coaxis.Repo.Migrations.ChangeSdgGoalDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:impact_goals) do
      modify :sdg_goal_type, :text, default: "life_below_water"
    end
  end

  def down do
    alter table(:impact_goals) do
      modify :sdg_goal_type, :text, default: "no_poverty"
    end
  end
end