defmodule Coaxis.Repo.Migrations.FixColumnNameIntentType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:projects), :intent_tupe, to: :intent_type
  end

  def down do
    rename table(:projects), :intent_type, to: :intent_tupe
  end
end
